Lower minimum allowed Fan RPM.
eriknn/ha-pax_ble pull request #28
Opened 2023-11-29 07:06 UTC by Nornode

Lower the minimume allowed rpm. 
This keeps the motor running, but has less significant impact on the air-flow. 

This is needed when the fan is used for forced air move inside->out and no backstop is installed and fan can't/should not be turned off.

2023-11-29 07:09 UTC, Nornode commented
In my situation my fan is installed in a house with very bad normal ventilation.
However now in the winter, it's unoccupied and there's no/minimal need to change the air inside.

The house is heated and running the fan at 800 RPM will cause unessesary heating costs. 
With this change, the fan should still run but keep the outside cold air from flowing inside.

Unfortunately I'm not currently at the house and can check the absolute minimal RPM required to have the motor running reliably.

2023-11-29 09:16 UTC, eriknn commented
Hi,
can you please try this in your local version first? I remember trying some lower speeds when first creating this integration, and if I recall correctly it didn’t work well for me - the fan started racing up and down!

2023-11-29 11:58 UTC, Nornode commented
Hi, 
Yeah, that's just that... 
I'm not currently at the location where this fan is running so I can't physically test it - it's 140km away...
I remember when I ran this with the Original Python package inside Node-Red i was able to run the fan on significantly lower RPM's.
At that time I had sucess.

If you want me to check on location, Please leave this PR open as I can't check it right now.

2023-11-30 09:32 UTC, luotinen commented
800 RPM seems to be lowest setting that it accepts. It still runs fine at that speed. It results in ~26 m3/h ventilation. (The default speed is 975 RPM ~35 m3/h).

Maybe the worry from the manufacturer has been that a strong gust of wind could resist the blade spinning and since the RPM is too slow, it will not be able to start spinning. This is not an issue for ON/OFF situations as the fans first spin at a faster rate.

2023-11-30 13:31 UTC, luotinen commented
I tested the commit:
600 works + starts OK
550 works + starts OK 
500 works + starts OK
450 works + starts OK
400 works + starts OK

It should be noted that this is probably highly dependent on the measurement conditions: installation type: roof/wall, presence of backflow mechanism, type, length and size of the ventilation duct, ventilation duct length and height difference, under/overpressure conditions, local weather conditions, room and outdoor temperature and pressure...

The measured RPM value was fluctuating -50 / +50 of the target value during the measurement. For 400 that's over +/- 10 % fluctuation.

=> 800 RPM is probably safe for most conditions.

2023-11-30 18:17 UTC, Nornode commented
Well, I think we are all beyond the reasons of making something secure. 
Is there anything that can break or diminish if we allow a slower rpm and the fan stalls?

I have for myself a pretty good use case where a lower than normally accepted speed would suffice. I also do not directly care if the fan stops, it will at some point start again.
I just want minimal air flow to minimise airflow as I can't and don't want switch it off completely.

My fan is wall mounted on a loft pushing air inside->out.

2023-11-30 22:53 UTC, eriknn requested changes
Increase to 500 and I'll approve it.

2023-12-01 08:44 UTC, Nornode commented
> Increase to 500 and I'll approve it.

Thanks! - Now increased to 500rpm

2023-12-01 10:48 UTC, merged

2023-12-01 10:50 UTC, eriknn commented
I am not sure what RPM the fan shows when stalled as I didn't actually pay attention to that, but I agree that this could just as well be handled in HA.